config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :promotions do
    member do 
      post 'generate_coupons'
      post 'approve'
    end
    get 'search', on: :collection
  end

  resources :product_categories, only: [:index, :show, :new, :create, :edit, :update, :destroy]

  resources :coupons, only: [] do
    post 'disable', on: :member
    get 'search', on: :collection
  end

  namespace :api, constrainsts: lambda{ |req| req.format == :json } do
    namespace :v1 do
      resources :coupons, only: [:show], param: :code
    end
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/coupon.rb
class Coupon < ApplicationRecord
  belongs_to :promotion

  enum status:  { active: 0, disabled: 10 }
  delegate :discount_rate, to: :promotion

  def as_json(options = {})
    super( { methods: :discount_rate }.merge(options) )
  end

  def self.search(query)
    Coupon.find_by(code: query)
  end
end

app/models/product_category.rb
class ProductCategory < ApplicationRecord
    validates :name, :code, presence: true
    validates :code, uniqueness: true
end

app/models/promotion.rb
class Promotion < ApplicationRecord
    belongs_to :user
    has_many :coupons , dependent: :restrict_with_error
    has_one :promotion_approval
    has_one :approver, through: :promotion_approval, source: :user

    validates :name, :code, :discount_rate, :coupon_quantity, 
              :expiration_date, presence: true
    validates :code, :name, uniqueness: true
    SERARCHABLE_FIELDS = %w[name code description].freeze

    def generate_coupons!
        return if coupons?

        (1..coupon_quantity).each do |number|
            coupons.create!(code: "#{code}-#{'%04d' % number}")
        end
    end

    #TODO: fazer testes para esse método
    def coupons? 
        coupons.any?
    end

    # TODO: Trocar para busca Kaminari - faz paginação
    def self.search(query)
        # where('name LIKE ?', "%#{query.downcase}%")
        # pode limitar o total de retorno para 5
        # where('name LIKE ?', "%#{query}%").limit(5)
        where(
            SERARCHABLE_FIELDS
                .map { |field| "#{field} LIKE :query"}
                .join(' OR '),
            query: "%#{query}%"
         ).limit(5)
    end

    def approved?
        promotion_approval.present?
    end

    def can_approve?(current_user)
        user != current_user
    end
end

app/models/promotion_approval.rb
class PromotionApproval < ApplicationRecord
  belongs_to :promotion
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :promotions, dependent: :destroy
  has_many :promotion_approvals, dependent: :nullify
  has_many :approved_promotions, through: :promotion_approvals, source: :promotion
end

app/controllers/api/v1/api_controller.rb
class Api::V1::ApiController < ActionController::API
    respond_to :json

    rescue_from ActiveRecord::RecordNotFound, with: :not_found_error

    private

        def not_found_error
            head 404
        end
end

app/controllers/api/v1/coupons_controller.rb
class Api::V1::CouponsController < Api::V1::ApiController
    def show
        @coupon = Coupon.active.find_by!(code: params[:code])
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
    def disable
        @coupon = Coupon.find(params[:id])
        @coupon.disabled!
        redirect_to @coupon.promotion, notice: t('.success', code: @coupon.code)
    end

    def search
        @coupon = Coupon.search(params[:q])
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
    end
end

app/controllers/product_categories_controller.rb
class ProductCategoriesController < ApplicationController
    before_action :authenticate_user!
    before_action :set_product_category, only: %i[show edit update destroy]

    def index
        @product_categories = ProductCategory.all
    end

    def show
    end

    def new
        @product_category = ProductCategory.new
    end

    def create
        @product_category = ProductCategory.new(product_params)
        if @product_category.save
            redirect_to @product_category
        else
            render :new
        end
    end

    def edit
    end

    def update
        return redirect_to @product_category if @product_category.update(product_params)

        render :edit
    end

    def destroy
        if @product_category.destroy
            redirect_to product_categories_path, notice: t('.success')
        else
            redirect_to @product_category, notice: t('.failed')
        end
    end

    private

        def set_product_category
            @product_category = ProductCategory.find(params[:id])
        end

        def product_params
            params
                .require(:product_category)
                .permit(:name, :code)
        end
end

app/controllers/promotions_controller.rb
class PromotionsController < ApplicationController
    before_action :authenticate_user!
    before_action :set_promotion, only: %i[show edit update destroy 
                                           generate_coupons approve]
    before_action :can_be_approved, only: [:approve]

    def index
        @promotions = Promotion.all
    end

    def show
    end

    def new
        @promotion = Promotion.new
    end

    def create
        @promotion = current_user.promotions.new(promotion_params)
        if @promotion.save
            redirect_to @promotion
        else
            render :new
        end
    end

    def generate_coupons
        @promotion.generate_coupons!
        redirect_to @promotion, notice: t('.success')
    end

    def edit
    end

    def update
        return redirect_to @promotion if @promotion.update(promotion_params)

        render :edit
    end

    def destroy
        # @coupons = Coupon.where(promotion: @promotion.id)
        # @coupons.each do |coupon|
        #     coupon.destroy
        # end

        if @promotion.destroy
            redirect_to promotions_path, notice: t('.success')
        else
            redirect_to @promotion, notice: t('.failed')
        end
    end

    def search
        @promotions = Promotion.search(params[:q])
        render :index
    end

    def approve
        current_user.promotion_approvals.create!(promotion: @promotion)
        PromotionMailer
          .with(promotion: @promotion, approver: current_user)
          .approval_email.deliver_now
        # PromotionMailer.approval_email(@promotion, current_user).deliver_now
        redirect_to @promotion, notice: t('.approved')
    end

    private

        def set_promotion
            @promotion = Promotion.find(params[:id])
        end

        def promotion_params
            params
                .require(:promotion)
                .permit(:name,  :expiration_date, :description,
                        :discount_rate, :code, :coupon_quantity)
        end

        # autorização
        def can_be_approved
            redirect_to @promotion, 
            alert: t('.disallowed') unless @promotion.can_approve?(current_user)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/coupons/search.html.erb
<%= link_to t('buttons.back'), root_path %>

<%= form_with url: search_coupons_path, method: :get do |f| %>
    <%= f.label :q, 'Buscar' %>
    <%= f.text_field :q %>
    <%= f.submit 'Buscar' %>
<% end %>

<% if @coupon.nil? %>
   <h3>Cupom não encontrado</h3>
<% else %>
    <dl>
        <dt>Cupom<%= @coupon.code %> </dt>
        <dd><%= @coupon.status %></dd>
    </dl>
    <br>
    <dl>
        <dt>Nome</dt>
        <dd><%= @coupon.promotion.name %></dd>
        <dt>Descrição</dt>
        <dd><%= @coupon.promotion.description %></dd>
        <dt>Desconto</dt>
        <dd><%= number_to_percentage @coupon.promotion.discount_rate, precision: 2 %></dd>
        <dt>Código</dt>
        <dd><%= @coupon.promotion.code %></dd>
        <dt>Data de término</dt>
        <dd><%= @coupon.promotion.expiration_date %></dd>
        <dt>Quantidade de cupons</dt>
        <dd><%= @coupon.promotion.coupon_quantity %></dd>
    </dl>
<% end %>

app/views/home/index.html.erb
<h1>Promotion System</h1>
<h3>Boas vindas ao sistema de gestão de promoções</h3>

<br>
<button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="top" title="Tooltip on top">
  Tooltip on top
</button>
<button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="right" title="Tooltip on right">
  Tooltip on right
</button>
<button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="bottom" title="Tooltip on bottom">
  Tooltip on bottom
</button>
<button type="button" class="btn btn-secondary" data-bs-toggle="tooltip" data-bs-placement="left" title="Tooltip on left">
  Tooltip on left
</button>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PromotionSystem</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if user_signed_in? %>
        <%= link_to 'Sair',  destroy_user_session_path, method: :delete %>

        <%= current_user.email %>
        <li><%= link_to 'Promoções', promotions_path %></li>
        <li><%= link_to 'Cupons', search_coupons_path %></li>
        <li><%= link_to 'Categorias de produtos', product_categories_path %></li>
      <% else %>
        <%= link_to 'Cadastrar', new_user_registration_path %>
        <%= link_to 'Entrar', new_user_session_path %>
      <% end %>
    </nav>

    <p><%= flash[:notice] %></p>
    <p><%= flash[:alert] %></p>
    <%= yield %>
  </body>
</html>

app/views/product_categories/_form.html.erb
<% if @product_category.errors.any? %>
<h4>Não foi possível salvar encontramos alguns erros: </h4>
    <ul>
        <% @product_category.errors.full_messages.each do |message| %>
            <li><%= message%> </li>
        <% end %>
    </ul>
<% end %>

<%= form_with model: @product_category do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.label :code %>
    <%= f.text_field :code %>
    <%= f.submit %>
<% end %>

app/views/product_categories/edit.html.erb
<h1>Editar uma categoria de produto </h1>
<%= render partial: 'form', locals: {product_category: @product_category } %>

app/views/product_categories/index.html.erb
<%= link_to t('buttons.back'), root_path %>
<%= link_to 'Registrar uma categoria de produto', new_product_category_path %>

<% if @product_categories.empty? %>
    <h3>Nenhuma categoria de produto cadastrada</h3>
<% end %>

<% @product_categories.each do |product_category| %>
    <h3><%= link_to product_category.name, product_category %></h3>
    <dl>
        <dt>Nome</dt>
        <dd><%= product_category.name %></dd>
        <dt>Código</dt>
        <dd><%= product_category.code %></dd>
    </dl>
<% end %>

app/views/product_categories/new.html.erb
<h1>Registrar uma promoção </h1>
<%= render partial: 'form', locals: {product_category: @product_category} %>

app/views/product_categories/show.html.erb
<%= link_to t('buttons.back'), product_categories_path %>
<%= link_to t('buttons.edit'), edit_product_category_path(@product_category) %>
<%= link_to t('buttons.destroy'), product_category_path(@product_category), 
                                            method: :delete, data: { confirm: t('.destroy_confirm') } %>

<h3>Lista de categorias de produtos</h3>
<ul>
    <li><%= ProductCategory.human_attribute_name(:name)%> - 
        <%= @product_category.code %> 
        : <%= @product_category.name %>
    </li>
</ul>

app/views/promotions/_form.html.erb
<% if @promotion.errors.any? %>
<h4>Não foi possível salvar encontramos alguns erros: </h4>
    <ul>
        <% @promotion.errors.full_messages.each do |message| %>
            <li><%= message%> </li>
        <% end %>
    </ul>
<% end %>

<%= form_with model: @promotion do |f| %>
    <div>
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>
    <div>
        <%= f.label :description %>
        <%= f.text_area :description %>
    </div>
    <div>
        <%= f.label :code %>
        <%= f.text_field :code %>
    </div>
    <div>
        <%= f.label :discount_rate %>
        <%= f.number_field :discount_rate, in: 0..100, step: 0.1 %>
    </div>
    <div>
        <%= f.label :coupon_quantity %>
        <%= f.number_field :coupon_quantity, min:1 %>
    </div>
    <div>
        <%= f.label :expiration_date %>
        <%= f.text_field :expiration_date %>
    </div>
    <%= f.submit button_title %>
<% end %>

app/views/promotions/edit.html.erb
<h1>Editar uma promoção </h1>
<%= render partial: 'form', locals: {promotion: @promotion, button_title: 'Editar promoção' } %>

app/views/promotions/index.html.erb
<%= link_to 'Voltar', root_path %>

<%= link_to 'Registrar uma promoção', new_promotion_path %>

<%= form_with url: search_promotions_path, method: :get do |f| %>
    <%= f.label :q, 'Buscar' %>
    <%= f.text_field :q %>
    <%= f.submit 'Buscar' %>
<% end %>

<% if @promotions.empty? %>
    <h3>Nenhuma promoção cadastrada </h3>
<% end %>

<!-- só execute se não estiver vazio -->
<% @promotions.each do |promotion| %>
    <h3><%= link_to promotion.name, promotion %></h3>
    <dl>
        <dt>Descrição</dt>
        <dd><%= promotion.description %></dd>
        <dt>Desconto <small>em porcentagem </small></dt>
        <dd><%= number_to_percentage promotion.discount_rate, separator: ',', precision: 2 %></dd>
    </dl>
<% end %>

app/views/promotions/new.html.erb
<h1>Registrar uma promoção </h1>
<%= render partial: 'form', locals: {promotion: @promotion, button_title: 'Criar promoção'} %>

app/views/promotions/show.html.erb
<%= link_to t('buttons.back'), promotions_path %>
<%= link_to t('buttons.edit'), edit_promotion_path(@promotion) %>
<%= link_to t('buttons.destroy'), promotion_path(@promotion), method: :delete, data: { confirm: t('.destroy_confirm') } %>

<h3><%= @promotion.name %></h3>
    <dl>
        <dt><%= Promotion.human_attribute_name(:description) %></dt>
        <dd><%= @promotion.description %></dd>
        <dt><%= Promotion.human_attribute_name(:discount_rate) %> <small>em porcentagem </small></dt>
        <dd><%= number_to_percentage @promotion.discount_rate, precision: 2 %></dd>
        <dt><%= Promotion.human_attribute_name(:code) %></dt>
        <dd><%= @promotion.code %></dd>
        <dt><%= Promotion.human_attribute_name(:expiration_date) %></dt>
        <dd><%= l @promotion.expiration_date %></dd>
        <dt><%= Promotion.human_attribute_name(:coupon_quantity) %> Quantidade de cupons </dt>
        <dd><%= @promotion.coupon_quantity %></dd>
    </dl>

    <% if @promotion.approved? %>
        <p>Aprovada por: <%= @promotion.approver.email %></p>
        <% if @promotion.coupons.empty? %>
            <%= link_to t('.generate_coupons'), generate_coupons_promotion_path(@promotion), method: :post %>
        <% end %>
    <% elsif @promotion.can_approve?(current_user) %>
        <%= link_to 'Aprovar', approve_promotion_path(@promotion), method: :post, data: { confirm: 'Tem certeza?' } %>
    <% end %>

    <% @promotion.coupons.each do |coupon|%>
        <div id="coupon-<%= coupon.code.parameterize %>">
            <p> <%= coupon.code  %> (<%= Coupon.human_attribute_name("status.#{coupon.status}") %>)</p>
            <% if coupon.active? %>
                <%= link_to 'Desabilitar', disable_coupon_path(coupon), method: :post, data: { disable_with: 'Estamos desabilitando....'} %>
            <% end %>
        </div>
    <% end %>